#!/bin/sh
# postinst script for abraflexi-kimai-importer

set -e

if [ "$1" = "configure" ]; then

    . /usr/share/debconf/confmodule
    db_get composer/WEB_USER
    WEBUSER=$RET

    mkdir -p /var/lib/composer /var/lib/abraflexi-kimai-importer /usr/lib/abraflexi-kimai-importer/
    chown $WEBUSER:$WEBUSER /var/lib/composer /var/lib/abraflexi-kimai-importer /usr/lib/abraflexi-kimai-importer/ -R
    su - $WEBUSER -s /bin/bash -c 'COMPOSER_HOME="/var/lib/composer" composer --no-dev -o install -d /usr/lib/abraflexi-kimai-importer/'

fi


#DEBHELPER#

exit 0
